### ISSUE TITLE
Mysql user creation fails, if user already exists

### ISSUE THREAD

**Issue by dbosen** [BurdaMagazinOrg/update-tester#2]
The script tries to create a new user for the database clone, this fails if the user already exists. You can modifiy the create user statement to use  "CREATE USER IF NOT EXISTS"

**Comment by mtodor** [comment]
Unfortunately "IF NOT EXISTS" option of "CREATE USER" statement is introduced in MySQL 5.7. So I provided solution with checking if user exists with SELECT statement before executing "CREATE USER".

Solution is provided in #4 pull request.
